# Generated by Django 3.0.4 on 2020-08-03 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dbms1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pt_id', models.CharField(max_length=100)),
                ('pt_name', models.CharField(max_length=100)),
                ('pt_output', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'result_ml',
            },
        ),
    ]
