# Generated by Django 3.0.8 on 2020-08-03 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front_end_main_app', '0002_auto_20200803_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pt_data',
            name='Patient_name',
        ),
    ]
