from django import forms

#this is user input form which will take values from user
class Patient_input_form(forms.Form):
    Patient_name = forms.CharField(label="Patient Name", max_length=100,required=False)
    Patient_id = forms.CharField(label="Patient Id", max_length=100, required=False)
    HR = forms.CharField(label="HR", max_length=100, required=False)
    O2Sat = forms.CharField(label="O2Sat", max_length=100, required=False)
    Temp = forms.CharField(label="Temp", max_length=100, required=False)
    SBP = forms.CharField(label="SBP ", max_length=100, required=False)
    MAP= forms.CharField(label=" MAP", max_length=100, required=False)
    DBP= forms.CharField(label=" DBP", max_length=100, required=False)
    Resp= forms.CharField(label="Resp", max_length=100, required=False)
    EtCO2= forms.CharField(label="EtCO2 ", max_length=100, required=False)
    BaseExcess= forms.CharField(label="BaseExcess", max_length=100, required=False)
    HCO3= forms.CharField(label="HCO3 ", max_length=100, required=False)
    FiO2= forms.CharField(label=" FiO2", max_length=100, required=False)
    pH= forms.CharField(label="pH ", max_length=100, required=False)
    PaCO2 = forms.CharField(label="PaCO2 ", max_length=100, required=False)
    SaO2 = forms.CharField(label="SaO2 ", max_length=100, required=False)
    AST= forms.CharField(label=" AST", max_length=100, required=False)
    BUN= forms.CharField(label=" BUN", max_length=100, required=False)
    Alkalinephos= forms.CharField(label="Alkalinephos ", max_length=100, required=False)
    Calcium= forms.CharField(label="Calcium ", max_length=100, required=False)
    Chloride = forms.CharField(label="Chloride ", max_length=100, required=False)
    Creatinine = forms.CharField(label="Creatinine ", max_length=100, required=False)
    Bilirubin_direct= forms.CharField(label="Bilirubin_direct ", max_length=100, required=False)
    Glucose = forms.CharField(label="Glucose", max_length=100, required=False)
    Lactate = forms.CharField(label="Lactate", max_length=100, required=False)
    Magnesium = forms.CharField(label="Magnesium", max_length=100, required=False)
    Phosphate = forms.CharField(label="Phosphate", max_length=100, required=False)
    Potassium = forms.CharField(label="Potassium", max_length=100, required=False)
    Bilirubin_total = forms.CharField(label="Bilirubin_total", max_length=100, required=False)
    TroponinI= forms.CharField(label="TroponinI", max_length=100, required=False)
    Hct = forms.CharField(label="Hct", max_length=100, required=False)
    Hgb = forms.CharField(label="Hgb", max_length=100, required=False)
    PTT = forms.CharField(label="PTT", max_length=100, required=False)
    WBC = forms.CharField(label="WBC", max_length=100, required=False)
    Fibrinogen = forms.CharField(label="Fibrinogen", max_length=100, required=False)
    Platelets = forms.CharField(label="Platelets", max_length=100, required=False)
    Age = forms.CharField(label="Age", max_length=100, required=False)
    Gender = forms.CharField(label="Gender", max_length=100, required=False)
    HospAdmTime = forms.CharField(label="HospAdmTime", max_length=100, required=False)
    ICULOS = forms.CharField(label="ICULOS", max_length=100, required=False)